(import com.ahungry                :as ahungry    :fresh true)
(import com.ahungry.conc.atom      :as atom       :fresh true)
(import com.ahungry.db             :as db         :fresh true)
(import com.ahungry.db.sqlite      :as sqlite     :fresh true)
(import com.ahungry.db.pgsql       :as pgsql      :fresh true)
(import com.ahungry.gui            :as gui        :fresh true)
(import com.ahungry.gui.iup        :as iup        :fresh true)
(import com.ahungry.meta           :as meta       :fresh true)
(import com.ahungry.net            :as net        :fresh true)
(import com.ahungry.net.tcp.client :as tcp.client :fresh true)
(import com.ahungry.wire           :as wire       :fresh true)
(import com.ahungry.wire.json      :as json       :fresh true)

(printf "com.ahungry: %s"                 (ahungry/meta    :version))
(printf "com.ahungry.conc.atom: %s"       (atom/meta       :version))
(printf "com.ahungry.db: %s"              (db/meta         :version))
(printf "com.ahungry.db.sqlite: %s"       (sqlite/meta     :version))
(printf "com.ahungry.db.pgsql: %s"        (pgsql/meta      :version))
(printf "com.ahungry.gui: %s"             (gui/meta        :version))
(printf "com.ahungry.gui.iup: %s"         (iup/meta        :version))
(printf "com.ahungry.meta: %s"            (meta/meta       :version))
(printf "com.ahungry.net: %s"             (net/meta        :version))
(printf "com.ahungry.net.tcp.client: %s"  (tcp.client/meta :version))
(printf "com.ahungry.wire: %s"            (wire/meta       :version))
(printf "com.ahungry.wire.json: %s"       (json/meta       :version))

(pp (-> (tcp.client/http-get "http://httpbin.org/ip") json/decode))
(pp (-> (tcp.client/json-get "http://httpbin.org/ip")))

(pp sqlite/open)
(pp iup/main-loop)
