# -*- mode: dockerfile; -*-

# This should fully encapsulate building a minimal binary for Alpine headless

FROM alpine:3.12.0 AS build

RUN apk add --update \
  git \
  gcc \
  make \
  libcurl \
  curl-dev \
  postgresql-dev \
  libpq \
  sqlite-libs \
  sqlite-dev \
  libc-dev

RUN mkdir /app

RUN echo "Building off 1.13.0 (20201006a) Janet with fixed build script"

RUN git clone --depth=1 https://github.com/ahungry/janet /janet
WORKDIR /janet
RUN make
RUN make install

RUN echo Clone 20201006a
RUN git clone --depth=1 https://github.com/ahungry/ahungry-janet /app

WORKDIR /app

# RUN ./get-iup-linux-files.sh
ENV IUP none
ENV GUI no

RUN make all IUP=none GUI=no
RUN make local-lib IUP=none GUI=no
RUN make janet.bin IUP=none GUI=no
# COPY package-linux.sh /app/
# RUN ./package-linux.sh
RUN jpm install || echo "Not everything installed."

FROM alpine:3.12.0

RUN apk add --update \
  libcurl \
  libpq \
  make \
  sqlite-libs

COPY --from=build /app /app
COPY --from=build /usr/local/bin/janet /usr/local/bin/
COPY --from=build /usr/local/bin/jpm /usr/local/bin/

COPY --from=build /usr/local/lib/janet /usr/local/lib/janet
#RUN mkdir -p /usr/local/lib/janet

# COPY . /app
WORKDIR /app

CMD sh
